italiana/urls.py
# -*- coding: utf-8 -*-

from django.contrib import admin
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static

from .utils import redireccionar

admin.site.site_header = 'Gestión Asociación Italiana'
admin.site.site_title = 'Gestión Asociación Italiana'
admin.site.site_url = None

urlpatterns = [
    url(r'^$', redireccionar),
    url(r'^admin/', admin.site.urls),
    url(r'^movimientos/', include('movimientos.urls')),
    url(r'^actividades/', include('actividades.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  # lo necesita para funcionar en desarrollo

movimientos/urls.py
from django.conf.urls import url

from .views import caja, get_caja, imprimir_recibo, ReciboCreate, generar_caja

urlpatterns = [
    url(r'^caja/', caja),
    url(r'^get_caja/', get_caja),

    url(r'^recibo/add/(?P<pk>[0-9]+)', ReciboCreate.as_view(), name='recibo-add'),
    # url(r'^cobro/(?P<pk>[0-9]+)', generar_recibo),

    url(r'^imprimir_recibo/(?P<pk>[0-9]+)', imprimir_recibo),
]

movimientos/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

from actividades.models import Actividad
from clientes.models import Cliente


class FormaPago(models.Model):
    tipo = models.CharField(max_length=40, unique=True)

    def __str__(self):
        return self.tipo.encode('utf8')


class Recibo(models.Model):
    # egreso negativo y ingreso positivo
    monto = models.DecimalField(max_digits=8, decimal_places=2)
    fecha = models.DateTimeField(auto_now_add=True)
    num_recibo = models.IntegerField(unique=True)
    forma_pago = models.ForeignKey(FormaPago)
    actividad = models.ManyToManyField(Actividad)
    cliente = models.ForeignKey(Cliente)

    def __str__(self):
        return "%s | $%s | Numero de recibo: %s" % (self.cliente, self.monto, self.num_recibo)


class CierreCaja(models.Model):
    fecha = models.DateField(auto_now_add=True)
    total_efectivo = models.DecimalField(max_digits=8, decimal_places=2)
    total_tarjeta = models.DecimalField(max_digits=8, decimal_places=2)
    recibo_desde = models.CharField(max_length=8, unique=True)
    recibo_hasta = models.CharField(max_length=8, unique=True)

    def __str__(self):
        return "%s | $%d" % (self.fecha, self.total_efectivo + self.total_tarjeta)

movimientos/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from datetime import datetime, timedelta

from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView
from django.http import JsonResponse, HttpResponseRedirect
from django.contrib import admin

from clientes.models import Cliente
from .models import Recibo, CierreCaja


def generar_caja(request):
    caja = CierreCaja()
    ultimo_cierre = CierreCaja.objects.all().last()

    recibos = Recibo.objects.filter(fecha__gt=ultimo_cierre.fecha + timedelta(days=1)).order_by("num_recibo")
    #recibos = Recibo.objects.all().order_by("num_recibo")

    caja.recibo_desde = recibos[0].num_recibo
    caja.recibo_hasta = recibos[len(recibos) - 1].num_recibo

    total_efectivo = 0
    total_tarjeta = 0
    for recibo in recibos:
        if recibo.forma_pago.tipo == "Efectivo":
            total_efectivo += recibo.monto
        else:
            total_tarjeta += recibo.monto

    caja.total_efectivo = total_efectivo
    caja.total_tarjeta = total_tarjeta

    caja.save()

    return HttpResponseRedirect("../")


def caja(request):

    context = {
        "title": "caja"
    }

    return render(request, 'movimientos/caja.html', context)


def get_caja(request):

    mes = datetime.today().month
    cajas = CierreCaja.objects.filter(fecha__month=mes)

    lista = []
    for caja in cajas:
        dic = {}
        dic['fecha'] = caja.fecha
        dic['recibo_desde'] = caja.recibo_desde
        dic['recibo_hasta'] = caja.recibo_hasta
        dic['total_tarjeta'] = caja.total_tarjeta
        dic['total_efectivo'] = caja.total_efectivo
        lista.append(dic)

    return JsonResponse(lista)


class ReciboCreate(CreateView):
    model = Recibo
    fields = ["forma_pago"]

    def get_context_data(self, **kwargs):
        context = super(ReciboCreate, self).get_context_data(**kwargs)
        client_id = self.kwargs["pk"]
        cliente = Cliente.objects.get(pk=client_id)
        context["title"] = "Recibo"
        context["actividades"] = self.get_actividades(cliente)
        context["cliente"] = cliente
        context.update(admin.site.each_context(self.request))
        return context

    def get_actividades(self, cliente):
        actividades = cliente.actividades.all()
        return actividades

    def form_valid(self, form):
        actividades = self.request.POST.getlist("actividades[]", None)
        cliente_id = self.request.POST.get("cliente")
        monto = self.request.POST.get("monto")
        forma_pago_id = self.request.POST.get("forma_pago")
        try:
            num_recibo = Recibo.objects.all().latest('num_recibo').num_recibo + 1
        except Recibo.DoesNotExist:
            num_recibo = 1

        recibo = Recibo()
        recibo.num_recibo = num_recibo
        recibo.monto = monto
        recibo.cliente_id = cliente_id
        recibo.forma_pago_id = forma_pago_id
        recibo.save()

        if actividades:
            actividades = actividades[0].split(",")

            for actividad in actividades:
                recibo.actividad.add(actividad)

        # instance = form.save(commit=True)

        # return super(ReciboCreate, self).form_valid(form)
        return redirect('/movimientos/imprimir_recibo/%s' % (str(recibo.pk)))


def imprimir_recibo(request, pk):
    recibo = Recibo.objects.get(pk=pk)
    context = {
        "recibo": recibo,
    }

    return render(request, "movimientos/imprimir_recibo.html", context)

templates/movimientos/caja.html
<!DOCTYPE html>
<html>
<head>
	<title>{{ title }}</title>
</head>
<body>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script type="text/javascript">

	$(function() {
		$.getJSON("movimientos/get_caja", {}, function(data) {
			console.log(data);
		})
	});

</script>
</body>
</html>

templates/movimientos/caja_changelist.html
{% extends 'admin/change_list.html' %}


{% block object-tools %}
    <ul class="object-tools">
        <li>
            <a href="generar_caja/" class="addlink">Generar caja</a>
        </li>
    </ul>
{% endblock %}

{% block content %}
    {% block content_title %}{% endblock %}
    <h1>Lista de cajas diarias</h1>
    {{ block.super }}
{% endblock %}

templates/movimientos/imprimir_recibo.html
{% load static %}
<html lang="es">
<head>
    <link rel="stylesheet" href="{% static 'css/recibo.css' %}">
    <script src="{% static 'js/numerosALetras.js' %}"></script>
</head>

<body onLoad="numerosLetras()">
    <div id="botonera">
        <button onClick="javascript:window.print()">Imprimir</button>
        <button onClick="back()">Volver</button>
    </div>


    <div id="page1">

        <div class="bordeRecibo">
            <header>
                <!-- Lado Izquierdo -->
                <div class="column left">
                    <div class="container">
                        <div class="row text-left">
                            {% if recibo.actividad.count == 1 %}
                                {% for actividad in recibo.actividad.all %}
                                    <img src="{{ actividad.imagen.url }}" alt="logo" width="100" height="85">
                                {% endfor %}
                            {% else %}
                                <img src="{% static 'img/logo_empresa.jpg' %}" alt="logo" width="208" height="85">
                            {% endif %}
                        </div>
                        <div class="row text-left negrita h3">Asoc. Italiana XX De Septiembre</div>
                        <div class="row text-left h3">Calle 20 Nº 654</div>
                        <div class="row text-left h3">Tel. 421776</div>
                    </div>
                </div>

                <!-- Lado Central -->
                <div class="column center text-center"> <span id="tipoComprobante">X</span>
                    <br>
                    <span id="leyendaTipoComprobante" class="preimpreso">DOCUMENTO<br>NO VALIDO<br>COMO<br>FACTURA</span>
                </div>

                <!-- Lado Derecho -->
                <div class="column right">
                    <div class="container">
                        <div id="lblComprobante" class="row text-center negrita h1">RECIBO</div>
                        <div id="lblNroCmp" class="row text-center negrita h2"><span class="preimpreso">Nro.</span> {{ recibo.num_recibo }}</div>
                        <div class="row text-center h3">ORIGINAL</div>
                        <div class="row text-center h3">&nbsp;</div>
                        <div class="row text-left h3">FECHA <span class="pull-right">{{ recibo.fecha|date:"d/m/Y" }}</span></div>

                    </div>
                </div>
            </header>

            <section>
                <span class="preimpreso">Recibimos de</span> {{ recibo.cliente }}
                <br>
                <span class="preimpreso">la cantidad de </span><span id="importeEnLetras"></span>
            </section>

            <section id="sectionMedioPago">
                <span class="preimpreso">Mediante</span>
                <div class="row">
                    <span>{{ recibo.forma_pago }}</span>
                    <span class="pull-right negrita importeEnPesos">{{ recibo.monto }}</span>
                </div>
            </section>

            <section>
                <span class="preimpreso">En concepto de</span>
                {% for actividad in recibo.actividad.all %}
                    <div class="row">
                        <span>{{ actividad }}</span>
                        <span name="a" class="pull-right negrita importeEnPesos">{{ actividad.precio }}</span>
                    </div>
                {% endfor %}

            </section>

            <footer>

                <section id="son"> <span class="preimpreso">SON:</span>
                    <output id="totalRecibo" class="negrita importeEnPesos">{{ recibo.monto }}</output>
                </section>

                <section id="firma">
                    <div id="hr" class="pull-right">&nbsp;</div>
                    <p class="text-right">Empresa</p>
                </section>

            </footer>
        </div><!-- bordeRecibo -->

        <div class="bordeRecibo" style="margin-top: 2px">
            <header>

                <!-- Lado Izquierdo -->
                <div class="column left">
                    <div class="container">
                        <div class="row text-left">
                            {% if recibo.actividad.count == 1 %}
                                {% for actividad in recibo.actividad.all %}
                                    <img src="{{ actividad.imagen.url }}" alt="logo" width="100" height="85">
                                {% endfor %}
                            {% else %}
                                <img src="{% static 'img/logo_empresa.jpg' %}" alt="logo" width="208" height="85">
                            {% endif %}
                        </div>
                        <div class="row text-left negrita h3">Asoc. Italiana XX De Septiembre</div>
                        <div class="row text-left h3">Calle 20 Nº 654</div>
                        <div class="row text-left h3">Tel. 421776</div>
                    </div>
                </div>

                <!-- Lado Central -->
                <div class="column center text-center"> <span id="tipoComprobante">X</span>
                    <br>
                    <span id="leyendaTipoComprobante" class="preimpreso">DOCUMENTO<br>NO VALIDO<br>COMO<br>FACTURA</span>
                </div>

                <!-- Lado Derecho -->
                <div class="column right">
                    <div class="container">
                        <div id="lblComprobante" class="row text-center negrita h1">RECIBO</div>
                        <div id="lblNroCmp" class="row text-center negrita h2"><span class="preimpreso">Nro.</span> {{ recibo.num_recibo }}</div>
                        <div class="row text-center h3">DUPLICADO</div>
                        <div class="row text-center h3">&nbsp;</div>
                        <div class="row text-left h3">FECHA <span class="pull-right">{{ recibo.fecha|date:"d/m/Y" }}</span></div>

                    </div>
                </div>
            </header>

            <section>
                <span class="preimpreso">Recibimos de</span> {{ recibo.cliente }}
                <br>
                <span class="preimpreso">la cantidad de </span><span id="importeEnLetrasD"></span>
            </section>

            <section id="sectionMedioPago">
                <span class="preimpreso">Mediante</span>
                <div class="row">
                    <span>{{ recibo.forma_pago }}</span>
                    <span class="pull-right negrita importeEnPesos">{{ recibo.monto }}</span>
                </div>
            </section>

            <section>
                <span class="preimpreso">En concepto de</span>
                {% for actividad in recibo.actividad.all %}
                    <div class="row">
                        <span>{{ actividad }}</span>
                        <span name="a" class="pull-right negrita importeEnPesos">{{ actividad.precio }}</span>
                    </div>
                {% endfor %}
            </section>

            <footer>
                <section id="son"> <span class="preimpreso">SON:</span>
                    <output id="totalRecibo" class="negrita importeEnPesos">{{ recibo.monto }}</output>
                </section>

                <section id="firma">
                    <div id="hr" class="pull-right">&nbsp;</div>
                    <p class="text-right">Empresa</p>
                </section>
            </footer>
        </div>
    </div>
</body>

<script type="text/javascript">

function numerosLetras() {

    let monto = "{{ recibo.monto }}";
    monto = monto.replace(",", ".");

    let letras = numeroALetras(monto);

    document.getElementById("importeEnLetras").innerHTML = letras;
    document.getElementById("importeEnLetrasD").innerHTML = letras;
}

function back() {
    location.href = "/admin/clientes/cliente/";
}

</script>

</html>

templates/movimientos/recibo_changelist.html
{% extends 'admin/change_list.html' %}

{% block content %}
    {% block content_title %}{% endblock %}
    <h1>Lista de recibos</h1>
    {{ block.super }}
{% endblock %}

templates/movimientos/recibo_form.html
{% extends "admin/base_site.html" %}
{% load i18n admin_urls static %}

{% block extrahead %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
{% endblock %}

{% block extrastyle %}
    {{ block.super }}
    <link rel="stylesheet" type="text/css" href="{% static "admin/css/forms.css" %}"/>

    <style>
        label[for="id_forma_pago"] {
            color: #333;
            font-weight: bold;
        }
    </style>

{% endblock %}

{% block breadcrumbs %}
    <div class="breadcrumbs">
        <a href="{% url 'admin:index' %}">{% trans 'Home' %}</a>
        &rsaquo; <a href="/admin/clientes/cliente/">{% trans 'Clientes' %}</a>
        &rsaquo; {% trans 'Cobrar' %}
    </div>
{% endblock %}

{% block content %}
    {% block content_title %}{% endblock %}
    <h1>Recibo de {{ cliente }}</h1>
    <div id="content-main">
        <form method="post">
            {% csrf_token %}
            <div>
                <fieldset class="module aligned ">
                    <input type="hidden" name="cliente" value="{{ cliente.id }}">

                    <div class="form-row">
                        <div>
                            {{ form }}
                        </div>
                    </div>
                    <div class="form-row">
                    <h2>Actividades a pagar:</h2>
                    {% for actividad in actividades %}
                        <div class="form-row">
                            <div>
                                <label class="required" for="{{ actividad.id }}">{{ actividad }} - {{ actividad.precio }}</label>
                                <input class="vTextField actividad" type="checkbox" id="{{ actividad.id }}" precio="{{ actividad.precio }}">
                            </div>
                        </div>
                    {% endfor %}
                    </div>
                    <input type="hidden" name="actividades[]" id="actividades"/>

                    <div class="form-row">
                        <div>
                            <label class="required">Monto total:</label>
                            <input type="number" name="monto" id="monto" readonly="readonly" value="0">
                        </div>
                    </div>
                    <br>

                </fieldset>
                <div class="submit-row">
                    <input type="button" class="default" id="generar_pago" value="Generar recibo">
                </div>
            </div>
        </form>

    </div>
    <script type="text/javascript">
        $(function() {
            actividades = [];
            $("#generar_pago").attr("disabled", true);

            $(".actividad").on("click", function() {
                let precio = parseInt($(this).attr("precio"));
                let total = parseInt($("#monto").val());

                if ($(this).is(":checked")) {
                    $("#monto").val(total + precio);
                    actividades.push($(this).attr("id"));
                } else {
                    let index = actividades.indexOf($(this).attr("id"));
                    if (index > -1) {
                        $("#monto").val(total - precio);
                        actividades.splice(index, 1);
                    }
                }

                if (actividades.length > 0) {
                    $("#generar_pago").attr("disabled", false);
                } else {
                    $("#generar_pago").attr("disabled", true);
                }
            });

            $("#generar_pago").on("click", function() {
                $("#actividades").val(actividades);
                $("form").submit();
            })
        });
    </script>

{% endblock %}